In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [6]:
## Define the vocabulary size
voc_size=10000

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3332, 7768, 3179, 6606],
 [3332, 7768, 3179, 4431],
 [3332, 9640, 3179, 4586],
 [1308, 4406, 8244, 2899, 353],
 [1308, 4406, 8244, 2899, 6344],
 [1181, 3332, 8598, 3179, 8117],
 [2136, 5303, 5121, 2899]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3332 7768 3179 6606]
 [   0    0    0    0 3332 7768 3179 4431]
 [   0    0    0    0 3332 9640 3179 4586]
 [   0    0    0 1308 4406 8244 2899  353]
 [   0    0    0 1308 4406 8244 2899 6344]
 [   0    0    0 1181 3332 8598 3179 8117]
 [   0    0    0    0 2136 5303 5121 2899]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\Laptop Care\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 399ms/step


array([[[ 0.04652264, -0.0378082 ,  0.02030375, -0.04151882,
         -0.00073497,  0.03923294,  0.0214462 ,  0.01945201,
          0.04260593, -0.03284265],
        [ 0.04652264, -0.0378082 ,  0.02030375, -0.04151882,
         -0.00073497,  0.03923294,  0.0214462 ,  0.01945201,
          0.04260593, -0.03284265],
        [ 0.04652264, -0.0378082 ,  0.02030375, -0.04151882,
         -0.00073497,  0.03923294,  0.0214462 ,  0.01945201,
          0.04260593, -0.03284265],
        [ 0.04652264, -0.0378082 ,  0.02030375, -0.04151882,
         -0.00073497,  0.03923294,  0.0214462 ,  0.01945201,
          0.04260593, -0.03284265],
        [ 0.00051202, -0.00249773,  0.00406653,  0.04340478,
         -0.01894187,  0.00040413,  0.02994896, -0.02502999,
         -0.00473758, -0.04132841],
        [-0.03649421, -0.02027225, -0.04354314,  0.04350188,
          0.03902599, -0.00391152,  0.02494456, -0.01016869,
          0.00868959, -0.04805034],
        [-0.03216378, -0.03163228,  0.00280748, -0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 3332, 7768, 3179, 6606], dtype=int32)

In [16]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>